name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: [3.8]
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Needed for `git describe --tags --abbrev=0` to work (used for getting the latest version tag)
    - name: Fetch full git history
      run: git fetch --prune --unshallow --tags

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Get tag name
      id: tag_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Check if release
      run: |
        TAG=$(git tag --points-at HEAD)
        if [ -z $TAG ]; then
          RELEASE=false;
        else
          RELEASE=true;
        fi
        echo $RELEASE
